project:
  type: website
  output-dir: _site

website:
  title: "Options Pricer"
  site-url: "https://ollie-gregory.github.io/black-scholes/"
  navbar:
    left:
      - text: "Instruments"
        menu:
          - text: "European"
            href: instruments/european.qmd
          - text: "American"
            href: instruments/american.qmd
      - text: "Market"
        href: market/market_data.qmd
      - text: "Models"
        menu:
          - text: "Black-Scholes"
            href: models/black_scholes.qmd
      - text: "Pricers"
        menu:
          - text: "Closed Form"
            href: pricers/closed_form.qmd
          - text: "Monte Carlo"
            href: pricers/monte_carlo.qmd
          - text: "Binomial Tree"
            href: pricers/tree.qmd
          - text: "Finite Differences"
            href: pricers/finite_differences.qmd

format:
  html:
    toc: true
    toc-depth: 3
  pdf:
    documentclass: article
    number-sections: true
    margin-bottom: 0.75in
    margin-left: 0.75in
    margin-right: 0.75in
    margin-top: 0.75in